# Generated by Django 4.2 on 2023-04-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='isProjectManager',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
