# Generated by Django 4.2 on 2023-05-03 21:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('externalAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
