# Generated by Django 4.2 on 2023-04-28 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('startDate', models.DateField(auto_now_add=True)),
                ('isFinished', models.BooleanField(default=False)),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='customUser.myuser')),
                ('writers', models.ManyToManyField(related_name='writers', to='customUser.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('lastModified', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customUser.myuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internalAPI.project')),
            ],
            options={
                'ordering': ['-creationDate', 'author'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customUser.myuser')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internalAPI.text')),
            ],
            options={
                'ordering': ['-creationDate', 'author'],
            },
        ),
    ]
