# Generated by Django 4.2 on 2023-05-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internalAPI', '0003_alter_text_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='markedAsFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(),
        ),
    ]
