# Generated by Django 4.2 on 2023-05-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internalAPI', '0004_text_markedasfinal_alter_project_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='markedAsFinal',
        ),
    ]
